initposition:       [0.011, 0.011, -0.1, 0.023, 0.12 ]

zeroposition:       [2.9496, 1.13446, -2.54818, 1.78896, 2.93075]

pregrasp_laying_mex: [2.97196, 2.2966, -2.36522, 3.34847, 3.036924]

pregrasp_standing_mex: [3.02221, 2.48996, -1.53309, 1.17502, 2.92980]

arm_out_of_view: [2.94958, 0.01564, -2.59489, 2.38586, 2.93068]
#[2.96930, 0.05919, -2.74733, 0.18922, 2.48745]

# grasp will be set by grasper
grasp_laying_mex: [] 

#PLATFORM POSES

platform_intermediate: [2.95008, 1.17834, -3.30993, 0.44033, 2.95170]
platform_left: [3.20691, 0.32942, -3.29642, 0.57904, 2.60902]
platform_right: [2.64898, 0.33072, -3.29658, 0.57911, 2.95179]
platform_centre: [2.95012, 0.36436, -3.31624, 0.45019, 2.95181]

platform_left_pre: [3.20691, 0.50000, -3.29642, 0.57904, 2.60902]
platform_right_pre: [2.64898, 0.50000, -3.29658, 0.57911, 2.95179]
platform_centre_pre: [2.95012, 0.50000, -3.31624, 0.45019, 2.95181]

#pregrasp_back_init: [2.9496, 1.18826, -3.1595, 0.14564, 2.9234]
#pregrasp_back:      [2.9496, 0.5475,  -3.1595, 0.14564, 2.9234]

field_of_view_sim: [0.011, 0.011, -0.1, 0.023, 2.9]

#LINE POSES (RIGHT TO LEFT)
line:
    line_1: [3.62224, 2.48888, -2.39791, 2.79911, 2.93070]
    line_2: [3.38231, 2.13810, -1.67897, 2.52825, 2.92261]
    line_3: [2.93732, 1.91937, -1.36863, 2.47464, 2.91953]
    line_4: [2.55503, 2.13815, -1.67899, 2.52825, 2.92261]
    line_5: [2.33276, 2.48885, -2.38858, 2.79900, 2.93077]

#ZIG ZAG POSES (RIGHT TO LEFT
zigzag:
    zz_1: [3.62224, 2.48888, -2.39791, 2.79911, 2.93070]
    zz_2: [3.33455, 2.35950, -1.91344, 2.25267, 2.92261]
    zz_3: [2.93732, 1.91937, -1.36863, 2.47464, 2.91953]
    zz_4: [2.60860, 2.35956, -1.91344, 2.25269, 2.92261]
    zz_5: [2.33276, 2.48885, -2.38858, 2.79900, 2.93077]
#
#line_1: [3.62224, 2.48888, -2.39791, 2.79911, 2.93070]
#line_2: [3.38231, 2.13810, -1.67897, 2.52825, 2.92261]
#line_3: [2.93732, 1.91937, -1.36863, 2.47464, 2.91953]
#line_4: [2.55503, 2.13815, -1.67899, 2.52825, 2.92261]
#line_5: [2.33276, 2.48885, -2.38858, 2.79900, 2.93077]

#ZIG ZAG POSES (RIGHT TO LEFT

#zz_1: [3.62224, 2.48888, -2.39791, 2.79911, 2.93070]
#zz_2: [3.33455, 2.35950, -1.91344, 2.25267, 2.92261]
#zz_3: [2.93732, 1.91937, -1.36863, 2.47464, 2.91953]
#zz_4: [2.60860, 2.35956, -1.91344, 2.25269, 2.92261]
#zz_5: [2.33276, 2.48885, -2.38858, 2.79900, 2.93077]

#manipulation timeout test parameters
left_tower: [2.5061, 0.0935881, -2.60509, 1.42038, 2.93033]
right_tower: [3.36525, 0.0935881, -2.72755, 1.40347, 2.93048]
